name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.12

      - name: Instalar dependências
        working-directory: "Analisador de texto"
        run: pip install -r requirements.txt

      - name: Instalar ferramentas de qualidade
        run: pip install pytest flake8

      - name: Rodar testes
        working-directory: "Analisador de texto"
        run: pytest

      - name: Rodar lint
        working-directory: "Analisador de texto"
        run: flake8 .
